### ISSUE TITLE
Write mdocs

### ISSUE THREAD

**Issue by rkjensen** [teamtomo/mdocfile#15]
This is a very cool tool! We actually just discussed writing something similar in the lab earlier this week. 

Maybe I just missed the obvious, but is there any function to write out the mdoc again after modifying values?

**Comment by alisterburt** [comment]
hey @rkjensen - appreciate the kind words and glad to hear you find the library useful 🙂 

You didn't miss anything obvious but there is some support. I'll write something out below and turn relevant part into a docs page for others

`mdocfile.read` returns a dataframe - this is convenient for analysis/data munging but not actually a good *model* for the contents of the file - global data is replicated across each section to keep things in a single dataframe etc.

Internally, the data is represented by a small set of [pydantic models](https://docs.pydantic.dev/latest/)
https://github.com/teamtomo/mdocfile/blob/3781d5a0f692617741312a77fa580b9413af14e5/mdocfile/mdoc.py#L9-L12
https://github.com/teamtomo/mdocfile/blob/3781d5a0f692617741312a77fa580b9413af14e5/mdocfile/global_data.py#L7-L18
https://github.com/teamtomo/mdocfile/blob/3781d5a0f692617741312a77fa580b9413af14e5/mdocfile/section_data.py#L7-L11

These models are built from the data in the file here
https://github.com/teamtomo/mdocfile/blob/3781d5a0f692617741312a77fa580b9413af14e5/mdocfile/mdoc.py#L14-L31

then converted into a dataframe here
https://github.com/teamtomo/mdocfile/blob/3781d5a0f692617741312a77fa580b9413af14e5/mdocfile/functions.py#L8-L36

To write an mdoc file, you would need to construct the models yourself then use the `Mdoc.to_string()` method
https://github.com/teamtomo/mdocfile/blob/3781d5a0f692617741312a77fa580b9413af14e5/mdocfile/mdoc.py#L33-L41

something like...

```python
with open('new_mdoc_file.mdoc', mode='w+') as file:
    file.write(mdoc.to_string())
```

Hope this helps? Will close this now but let me know if you still have any questions!

**Comment by alisterburt** [comment]
docs added at https://teamtomo.org/mdocfile/writing/
